services:
  app:
    image: golang:1.24-alpine
    container_name: natillera-go-app
    working_dir: /app
    volumes:
      - .:/app
      - ../natillera-shared:/natillera-shared
      - go-modules-natillera:/go/pkg/mod
    ports:
      - "8080:8080"
      - "40000:40000"
    environment:
      - GO_ENV=dev
      - DB_URL=mongodb://mongodb:27017/natillera
    command: >
      sh -c "go mod tidy && go mod download && go run ./cmd/"
    tty: true
    stdin_open: true
    networks:
      - natillera-network

networks:
  natillera-network:
    external: true

volumes:
  go-modules-natillera:
    external: true

#docker exec -it natillera-go-app go mod tidy
