services:
  networks:
    natillera-network:
      driver: bridge
  mongodb:
    image: mongo:8.0.8
    container_name: natillera-mongodb
    restart: unless-stopped
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root27017
    - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - natillera-mongodb-volume:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh natillera-mongodb:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - natillera-network
volumes:
  natillera-mongodb-volume:
    external: true