// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user.proto

package pb_generate_user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDataPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Names         string                 `protobuf:"bytes,4,opt,name=Names,proto3" json:"Names,omitempty"`
	Lastnames     string                 `protobuf:"bytes,5,opt,name=Lastnames,proto3" json:"Lastnames,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Theme         string                 `protobuf:"bytes,7,opt,name=Theme,proto3" json:"Theme,omitempty"`
	Photo         string                 `protobuf:"bytes,8,opt,name=Photo,proto3" json:"Photo,omitempty"`
	Password      string                 `protobuf:"bytes,9,opt,name=Password,proto3" json:"Password,omitempty"`
	RolId         string                 `protobuf:"bytes,10,opt,name=RolId,proto3" json:"RolId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Rol           *RolPB                 `protobuf:"bytes,13,opt,name=Rol,proto3" json:"Rol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataPB) Reset() {
	*x = UserDataPB{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataPB) ProtoMessage() {}

func (x *UserDataPB) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataPB.ProtoReflect.Descriptor instead.
func (*UserDataPB) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserDataPB) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserDataPB) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDataPB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDataPB) GetNames() string {
	if x != nil {
		return x.Names
	}
	return ""
}

func (x *UserDataPB) GetLastnames() string {
	if x != nil {
		return x.Lastnames
	}
	return ""
}

func (x *UserDataPB) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserDataPB) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserDataPB) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *UserDataPB) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserDataPB) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *UserDataPB) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserDataPB) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserDataPB) GetRol() *RolPB {
	if x != nil {
		return x.Rol
	}
	return nil
}

type RolPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Options       []*OptionPB            `protobuf:"bytes,6,rep,name=Options,proto3" json:"Options,omitempty"`
	OptionsRol    []*OptionsRolPB        `protobuf:"bytes,7,rep,name=OptionsRol,proto3" json:"OptionsRol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolPB) Reset() {
	*x = RolPB{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolPB) ProtoMessage() {}

func (x *RolPB) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolPB.ProtoReflect.Descriptor instead.
func (*RolPB) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RolPB) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RolPB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RolPB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RolPB) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RolPB) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RolPB) GetOptions() []*OptionPB {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RolPB) GetOptionsRol() []*OptionsRolPB {
	if x != nil {
		return x.OptionsRol
	}
	return nil
}

type OptionPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionPB) Reset() {
	*x = OptionPB{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionPB) ProtoMessage() {}

func (x *OptionPB) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionPB.ProtoReflect.Descriptor instead.
func (*OptionPB) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *OptionPB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OptionPB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OptionsRolPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolId         string                 `protobuf:"bytes,1,opt,name=RolId,proto3" json:"RolId,omitempty"`
	Option        *OptionPB              `protobuf:"bytes,2,opt,name=Option,proto3" json:"Option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionsRolPB) Reset() {
	*x = OptionsRolPB{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsRolPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsRolPB) ProtoMessage() {}

func (x *OptionsRolPB) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsRolPB.ProtoReflect.Descriptor instead.
func (*OptionsRolPB) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *OptionsRolPB) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *OptionsRolPB) GetOption() *OptionPB {
	if x != nil {
		return x.Option
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"\xc4\x02\n" +
	"\n" +
	"UserDataPB\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Names\x18\x04 \x01(\tR\x05Names\x12\x1c\n" +
	"\tLastnames\x18\x05 \x01(\tR\tLastnames\x12\x14\n" +
	"\x05Phone\x18\x06 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Theme\x18\a \x01(\tR\x05Theme\x12\x14\n" +
	"\x05Photo\x18\b \x01(\tR\x05Photo\x12\x1a\n" +
	"\bPassword\x18\t \x01(\tR\bPassword\x12\x14\n" +
	"\x05RolId\x18\n" +
	" \x01(\tR\x05RolId\x12\x1c\n" +
	"\tCreatedAt\x18\v \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\f \x01(\tR\tUpdatedAt\x12\x18\n" +
	"\x03Rol\x18\r \x01(\v2\x06.RolPBR\x03Rol\"\xdd\x01\n" +
	"\x05RolPB\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1c\n" +
	"\tCreatedAt\x18\x04 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x05 \x01(\tR\tUpdatedAt\x12#\n" +
	"\aOptions\x18\x06 \x03(\v2\t.OptionPBR\aOptions\x12-\n" +
	"\n" +
	"OptionsRol\x18\a \x03(\v2\r.OptionsRolPBR\n" +
	"OptionsRol\"@\n" +
	"\bOptionPB\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"G\n" +
	"\fOptionsRolPB\x12\x14\n" +
	"\x05RolId\x18\x01 \x01(\tR\x05RolId\x12!\n" +
	"\x06Option\x18\x02 \x01(\v2\t.OptionPBR\x06OptionB\x14Z\x12./pb_generate_userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*UserDataPB)(nil),   // 0: UserDataPB
	(*RolPB)(nil),        // 1: RolPB
	(*OptionPB)(nil),     // 2: OptionPB
	(*OptionsRolPB)(nil), // 3: OptionsRolPB
}
var file_user_proto_depIdxs = []int32{
	1, // 0: UserDataPB.Rol:type_name -> RolPB
	2, // 1: RolPB.Options:type_name -> OptionPB
	3, // 2: RolPB.OptionsRol:type_name -> OptionsRolPB
	2, // 3: OptionsRolPB.Option:type_name -> OptionPB
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
